### ISSUE TITLE
Sizing on smaller screens

### ISSUE THREAD

**Issue by ckluis** [bu/hColumns#2]
This model doesn't scale down on smaller screens.

Perhaps each section could have a title that would could be displayed vertically and already selected columns could collapse with just the title of that section displayed.  Clicking on it could open it up.  This would allow for deeper layers of navigation with less ackward scrolling.

**Comment by ghost** [comment]
css to the rescue :) 

.column-view-container{  width: 100%;text-align: justify; font-size: 0.1px; }
.column{ display: inline-block; background: #eee; width: 31%;margin-bottom: 3%; height: 250px;  margin-bottom: 2.5%; 
position: relative;
}   

.column-view-container::after{ content: ''; display: inline-block; width: 100%; }
.column-view-composition { display:block; white-space: nowrap; width: 100%; height: 250px; overflow:hidden; }
.column ul { position: absolute;  ; width: 100%; }   

@media screen and (max-width:600px) {
 .column-view-composition { 
display:block;white-space: nowrap;width: 100%;overflow:hidden;  
height:750px;
}

.column{ width: 100%;  margin-bottom: 5%; display: block;}
 .column ul { display: block; width: 100%;height: 250px; overflow-y: auto; list-style: none; } 

}
